import csv

# Complete list of food data: Food, Glycemic Index, Category
glycemic_index_data = [
    ["Food", "Glycemic Index", "Category"],
    ["Acerola", "20", "Low"],
    ["Acorns", "25", "Low"],
    ["Agave syrup", "15", "Low"],
    ["Almond", "15", "Low"],
    ["Almond milk", "30", "Low"],
    ["Almond oil", "25", "Low"],
    ["Almond paste", "35", "Low"],
    ["Amaranth", "70", "High"],
    ["Amaranth seeds", "35", "Low"],
    ["Apple", "42", "Low"],
    ["Apple cider", "40", "Low"],
    ["Apple juice", "40-50", "Low"],
    ["Apple sauce", "35", "Low"],
    ["Apricot", "34", "Low"],
    ["Apricots syrup", "60", "Moderate"],
    ["Artichoke", "20", "Low"],
    ["Asparagus", "15", "Low"],
    ["Avocado", "10", "Low"],
    ["Azuki Beans", "35", "Low"],
    ["Bamboo sprouts", "20", "Low"],
    ["Banana", "48", "Low"],
    ["Banana pie", "47", "Low"],
    ["Bananas dried", "48", "Low"],
    ["Balsamic vinegar", "5", "Low"],
    ["Barley flour", "30", "Low"],
    ["Barley groats", "25", "Low"],
    ["Basil", "5", "Low"],
    ["Basmati Rice", "45-50", "Low"],
    ["Beans cooked", "80", "High"],
    ["Beef ", "0", "Low"],
    ["Beef brains", "0", "Low"],
    ["Beef Stroganoff", "56", "Moderate"],
    ["Beetroot", "15", "Low"],
    ["Beetroot fresh", "30", "Low"],
    ["Beets boiled", "65", "Moderate"],
    ["Black currant", "15", "Low"],
    ["Black olives", "15", "Low"],
    ["Blackberry", "25", "Low"],
    ["Blueberries", "25-53", "Low"],
    ["Boiled beef tongue", "0", "Low"],
    ["Boiled chicken breast", "0", "Low"],
    ["Boiled lamb", "0", "Low"],
    ["Boiled lean beef", "0", "Low"],
    ["Boiled sweetcorn", "60", "Moderate"],
    ["Boiled veal", "0", "Low"],
    ["Braised Cauliflower", "15", "Low"],
    ["Bran", "15", "Low"],
    ["Bran bread", "65", "Moderate"],
    ["Bread oatmeal", "47", "Low"],
    ["Breadfruit", "65", "Moderate"],
    ["Brewers yeast", "35", "Low"],
    ["Broccoli", "15", "Low"],
    ["Broccoli cooked", "45", "Low"],
    ["Brown rice", "50", "Low"],
    ["Brown sugar", "70", "High"],
    ["Brown yeast bread", "65", "Moderate"],
    ["Brussels sprouts", "15", "Low"],
    ["Buckwheat", "50", "Low"],
    ["Buckwheat bread", "50", "Low"],
    ["Buckwheat flour", "40", "Low"],
    ["Buckwheat noodles", "59", "Moderate"],
    ["Buckwheat pancakes", "40", "Low"],
    ["Buckwheat Pasta", "40", "Low"],
    ["Buckwheat porridge", "40", "Low"],
    ["Bulgur", "55", "Low"],
    ["Butter", "0-14", "Low"],
    ["Butter cookies", "55", "Moderate"],
    ["Canned Grapefruit", "47", "Low"],
    ["Canned pears", "55", "Moderate"],
    ["Canned vegetables", "65", "Moderate"],
    ["Capellini pasta", "45", "Low"],
    ["Caraway", "5", "Low"],
    ["Carob powder", "15", "Low"],
    ["Carrot", "30", "Low"],
    ["Carrot", "85", "High"],
    ["Carrot Juice", "40", "Low"],
    ["Cashew nuts", "15-25", "Low"],
    ["Cassava", "55", "Moderate"],
    ["Cauliflower", "15", "Low"],
    ["Celery", "15", "Low"],
    ["Celery boiled", "85", "High"],
    ["Cereals", "45", "Low"],
    ["Chayote", "50", "Low"],
    ["Cheddar", "0", "Low"],
    ["Cheese", "0", "Low"],
    ["Cherry", "25", "Low"],
    ["Cherry plum", "25", "Low"],
    ["Chia Seeds", "30", "Low"],
    ["Chicken", "0", "Low"],
    ["Chickpea flour", "35", "Low"],
    ["Chickpeas", "10-35", "Low"],
    ["Chicory", "15-40", "Low"],
    ["Chilli", "15", "Low"],
    ["Chinese cabbage", "20", "Low"],
    ["Chinese noodles", "35", "Low"],
    ["Chips salted", "42", "Low"],
    ["Chocolate", "23-49", "Low"],
    ["Chocolate 70% cocoa", "25", "Low"],
    ["Chocolate milk", "34", "Low"],
    ["Chocolate powder with sugar", "60", "Moderate"],
    ["Cinnamon", "5", "Low"],
    ["Cocoa Powder", "20", "Low"],
    ["Coconut", "45", "Low"],
    ["Coconut Milk", "40", "Low"],
    ["Coconut Sugar", "35", "Low"],
    ["Cookies sugar free", "50", "Low"],
    ["Corn chips", "63", "Moderate"],
    ["Corn flakes", "85", "High"],
    ["Corn flour", "70", "High"],
    ["Corn pasta", "68", "Moderate"],
    ["Corn syrup", "15", "Low"],
    ["Cottage cheese", "30", "Low"],
    ["Cranberries", "45", "Low"],
    ["Cranberry Juice", "50", "Low"],
    ["Cream", "25-33", "Low"],
    ["Dark Chocolate", "20", "Low"],
    ["Dessert Banana", "60", "Moderate"],
    ["Donuts", "75", "High"],
    ["Dried dates", "40", "Low"],
    ["Dried fruits", "60", "Moderate"],
    ["Dried Peaches", "35", "Low"],
    ["Duck", "0", "Low"],
    ["Durum wheat vermicelli", "35", "Low"],
    ["Egg", "0", "Low"],
    ["Eggplant", "20", "Low"],
    ["Eggplant Caviar", "40", "Low"],
    ["Energy bar", "50", "Low"],
    ["Feta Cheese", "30", "Low"],
    ["Fig", "35", "Low"],
    ["French fries", "75", "High"],
    ["Fructose", "20", "Low"],
    ["Germinated bread", "35", "Low"],
    ["Glucose", "96-100", "High"],
    ["Honey", "60", "Moderate"],
    ["Ice cream", "46", "Low"],
    ["Instant noodles", "52", "Moderate"],
    ["Jam", "51", "Moderate"],
    ["Jasmine Rice", "60", "Moderate"],
    ["Ketchup", "55", "Moderate"],
    ["Lasagna", "47", "Low"],
    ["Lychee", "50", "Low"],
    ["Milk bread", "60", "Moderate"],
    ["Muesli", "56-65", "Moderate"],
    ["Oatmeal cookies", "55", "Moderate"],
    ["Olive oil", "0", "Low"],
    ["Orange juice", "45-48", "Low"],
    ["Peanut Butter", "25", "Low"],
    ["Peas", "35", "Low"],
    ["Pineapple Juice", "50", "Low"],
    ["Pizza", "60", "Moderate"],
    ["Popcorn", "55", "Moderate"],
    ["Rice Bread", "70", "High"],
    ["Rice Syrup", "100", "High"],
    ["Rye crackers", "64", "Moderate"],
    ["Soy milk", "30", "Low"],
    ["White rice standard", "70", "High"],
    ["Yogurt", "32-35", "Low"]
]

# Write the complete data into a CSV file
csv_filename = "glycemic_index_data.csv"
with open(csv_filename, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(glycemic_index_data)

print(f"Glycemic index data successfully saved to {csv_filename}")

